### ISSUE TITLE
autofarm or autofarmv2 ?

### ISSUE THREAD

**Issue by MaThlff** [tzechco/pls-donate-autofarm#6]
what's the difference between them ?

**Comment by MaThlff** [comment]
also i have this problem 
![image](https://user-images.githubusercontent.com/99496062/197214371-31263b27-74da-4c3a-b61f-f1318206b405.png)

**Comment by tzechco** [comment]
Autofarm v2 is the new version I’m working on. It’s still in testing but feel free to try it. 

> also i have this problem
> ![image](https://user-images.githubusercontent.com/99496062/197214371-31263b27-74da-4c3a-b61f-f1318206b405.png)

How much have you raised? There are some issues with Roblox censoring large numbers.

**Comment by tzechco** [comment]
It didn’t work because I made a typo in the code and just now realized.

It seems Roblox censorship does not like numbers over 800. Bypassing the censorship might be possible so I’ll look into it it.

**Comment by tzechco** [comment]
Bypassing was not possible but I added a new option to server hop when your booth gets censored which seems to fix the issue.
